//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Medicene_Store_Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase
    {
        public int Pur_ID { get; set; }
        public int DealerID { get; set; }
        public string ProductID { get; set; }
        public System.DateTime PurDate { get; set; }
        public int Quatity { get; set; }
        public decimal Price { get; set; }
        public decimal Total_Amount { get; set; }
    
        public virtual Dealer Dealer { get; set; }
        public virtual Product Product { get; set; }
    }
}
