//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Medicene_Store_Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaffSalery
    {
        public int Salarey_ID { get; set; }
        public string StaffID { get; set; }
        public double Salery { get; set; }
    
        public virtual StaffDetail StaffDetail { get; set; }
    }
}
