//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Medicene_Store_Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaffDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StaffDetail()
        {
            this.StaffSaleries = new HashSet<StaffSalery>();
        }
    
        public string UserName { get; set; }
        public string Password { get; set; }
        public string StaffID { get; set; }
        public string Name { get; set; }
        public double Contact { get; set; }
        public string Address { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StaffSalery> StaffSaleries { get; set; }
    }
}
